// Booking details checked against the linked property/listing sources on 2 October 2026.
export const nearbyStays = [
  {
    name: "De Papi’s Hotel",
    address: "12 Eric Oharisi Street, Slaughter Road, Otovwodo, Ughelli",
    stars: 4,
    ratingSource: "Goibibo",
    sourceUrl: "https://www.goibibo.com/hotels-international/de-papis-hotel-in-ughelli-north-8868645635308068753/",
    bookingUrl: "https://www.goibibo.com/hotels-international/de-papis-hotel-in-ughelli-north-8868645635308068753/",
    bookingLabel: "Check rooms on Goibibo",
    bookingNote: "Choose your arrival and departure dates on the booking page, then check the available rooms and cancellation terms.",
    review: "",
    phone: "",
  },
  {
    name: "Oges Hotel Annex",
    address: "Erieta Street, along Ekrejebor Road, Ughelli",
    stars: 4,
    ratingSource: "Google Hotels",
    sourceUrl: "https://www.google.com/travel/hotels/entity/CgsI7efS5PL28JG5ARAB",
    bookingUrl: "https://www.google.com/travel/hotels/entity/CgsI7efS5PL28JG5ARAB",
    bookingLabel: "Open hotel & contact details",
    bookingNote: "Open the hotel listing and use “Contact this property” to ask for rates and reserve your room directly.",
    review: "4.3 / 5 · 3 Google reviews",
    phone: "",
  },
  {
    name: "G12 Hotels & Suite",
    address: "Opposite Ughelli Township Stadium, Otovwodo, Ughelli",
    stars: 0,
    ratingSource: "Official hotel website",
    sourceUrl: "https://g12hotels.com/contact/",
    bookingUrl: "https://g12hotels.com/",
    bookingLabel: "View rooms & reservations",
    bookingNote: "Call or WhatsApp the hotel on 0707 794 4680 with your travel dates and the number of rooms you need.",
    review: "",
    phone: "+2347077944680",
  },
] as const;
