"use client";
import {useState,useRef,useEffect,type FormEvent} from 'react';
import {api} from '../client-api';
import {Skeleton} from '@/components/ui/skeleton';
export default function Scanner(){
 const [ready,setReady]=useState(false),[loading,setLoading]=useState(true),[password,setPassword]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false),[manual,setManual]=useState(''),[search,setSearch]=useState(''),[matches,setMatches]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[count,setCount]=useState(1);
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),frame=useRef(0),locked=useRef(false),requestId=useRef(''),attemptCount=useRef<number|null>(null);
 function stop(){cancelAnimationFrame(frame.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCamera(false)}
 async function lookup(pass:string){if(locked.current)return;locked.current=true;stop();setBusy(true);setError('');setMessage('');try{const d=await api('scan/lookup',{method:'POST',body:JSON.stringify({pass})});setSelected(d);setCount(1);requestId.current=crypto.randomUUID();attemptCount.current=null;setMatches([])}catch(e){setError((e as Error).message)}finally{setBusy(false);locked.current=false}}
 useEffect(()=>{api('scan/search',{method:'POST',body:JSON.stringify({name:'__access_check__'})}).then(()=>setReady(true)).catch(()=>{}).finally(()=>setLoading(false));return()=>{cancelAnimationFrame(frame.current);stream.current?.getTracks().forEach(t=>t.stop())}},[]);
 async function signIn(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('auth/login',{method:'POST',body:JSON.stringify({role:'usher',password})});setPassword('');setReady(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function start(){stop();setError('');setMessage('');setSelected(null);setCamera(true);try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera scanning isn’t available here. Use the pass link, name search or a QR image instead.');const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:720}},audio:false});stream.current=media;await new Promise<void>(r=>requestAnimationFrame(()=>r()));if(!video.current){media.getTracks().forEach(t=>t.stop());throw new Error('Please start the camera again.')}video.current.srcObject=media;await video.current.play();const {default:jsQR}=await import('jsqr');const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});let last=0;const tick=(time:number)=>{if(!stream.current||!video.current||!ctx)return;const v=video.current;if(time-last>180&&v.readyState>=2){last=time;canvas.width=v.videoWidth;canvas.height=v.videoHeight;ctx.drawImage(v,0,0);const im=ctx.getImageData(0,0,canvas.width,canvas.height);const qr=jsQR(im.data,im.width,im.height,{inversionAttempts:'dontInvert'});if(qr){void lookup(qr.data);return}}frame.current=requestAnimationFrame(tick)};frame.current=requestAnimationFrame(tick)}catch(e){stop();setError((e as Error).message||'Camera permission was not granted. Use the pass link or name search.')}}
 async function readImage(file:File){setError('');try{const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Couldn’t read the image.');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const im=ctx.getImageData(0,0,canvas.width,canvas.height),{default:jsQR}=await import('jsqr');const qr=jsQR(im.data,im.width,im.height);if(!qr)throw new Error('No QR was found in that photo. Try a clearer image.');await lookup(qr.data)}catch(e){setError((e as Error).message)}}
 async function find(e:FormEvent){e.preventDefault();setBusy(true);setError('');setSelected(null);stop();try{const d=await api('scan/search',{method:'POST',body:JSON.stringify({name:search})});setMatches(d.guests);if(!d.guests.length)setMessage('No matching guests. Check the name with the family.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function admit(){setBusy(true);setError('');setMessage('');try{if(attemptCount.current!==null&&attemptCount.current!==count)throw new Error('Refresh this pass before changing a previous entry attempt.');attemptCount.current=count;const d=await api('scan/checkin',{method:'POST',body:JSON.stringify({pass:selected.pass,count,requestId:requestId.current})});setSelected({...selected,guest:d.guest});setMessage(`${d.alreadyRecorded?'Already recorded':'Entry recorded'}: ${count} ${count===1?'person':'people'} for ${d.guest.name}.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!ready)return <main className="admin-login"><a href="/" className="wordmark">B &amp; B</a><p className="eyebrow">12 DECEMBER 2026 · ENTRY DESK</p><h1>Welcome<br/>the guests.</h1>{loading?<Skeleton className="h-32 rounded-none"/>:<form onSubmit={signIn}><label htmlFor="usher-password">Usher password</label><input id="usher-password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="button" disabled={busy}>{busy?'Opening…':'Open entry desk'}</button></form>}{error&&<p role="alert" className="form-message">{error}</p>}<p className="secondary">Organisers can sign in at the family desk and open this page.</p><a className="text-link" href="/organiser">Organiser sign-in</a></main>;
 const remaining=selected?Math.max(0,selected.guest.allowedGuests-selected.guest.checkedIn):0;
 const valid=selected?.guest.status==='approved'&&selected?.guest.attending!=='no';
 return <main className="scanner-page"><header className="admin-header"><a href="/" className="wordmark">B &amp; B</a><a href="/organiser">Family desk</a></header><p className="eyebrow">ENTRY DESK · 12 DECEMBER 2026</p><h1>A warm welcome.<br/>A quick check.</h1><p>Scan the guest’s QR, then confirm how many people are entering. A working internet connection is needed to verify and record entry.</p><div className="scan-actions"><button className="button" disabled={busy} onClick={()=>camera?stop():void start()}>{camera?'Stop camera':'Scan an entry QR'}</button><label className="text-button qr-file">Read a QR image<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void readImage(f);e.target.value=''}}/></label></div>{camera&&<div className="camera-area"><video ref={video} playsInline muted/><p>Hold the QR steady inside the camera view.</p></div>}{error&&<p role="alert" className="form-message">{error}</p>}{message&&<p role="status" className="form-message">{message}</p>}
 {selected&&<section className={'scan-result '+(valid&&remaining>0?'valid-pass':'inactive-pass')}><p className="eyebrow">{!valid?'PASS NOT ACTIVE':remaining===0?'PARTY ALREADY ADMITTED':'CONFIRMED GUEST'}</p><h2>{selected.guest.name}</h2><p>{selected.guest.allowedGuests} places confirmed · {selected.guest.checkedIn} already entered</p>{valid&&remaining>0?<><label htmlFor="entering-count">People entering now ({remaining} remaining)</label><input id="entering-count" type="number" min="1" max={remaining} value={count} disabled={busy||attemptCount.current!==null} onChange={e=>setCount(Number(e.target.value))}/><button className="button" disabled={busy||count<1||count>remaining} onClick={()=>void admit()}>{busy?'Recording entry…':attemptCount.current!==null?'Confirm / retry this entry':'Confirm entry'}</button>{attemptCount.current!==null&&<button className="text-button" onClick={()=>void lookup(selected.pass)}>Refresh pass for the next arrival</button>}</>:<p>{valid?'This pass has used its full allowance. Ask the family before admitting anyone else.':'Please ask the family to confirm this guest. Do not admit using this pass.'}</p>}<button className="text-button" onClick={()=>{setSelected(null);setMessage('');setError('');attemptCount.current=null}}>Next guest</button></section>}
 <div className="scan-fallbacks"><form onSubmit={e=>{e.preventDefault();void lookup(manual)}}><h2>Use the pass link</h2><label htmlFor="manual-pass">Guest pass link or code</label><input id="manual-pass" value={manual} onChange={e=>setManual(e.target.value)} required/><button className="button" disabled={busy}>Check pass</button></form><form onSubmit={find}><h2>Look up a name</h2><label htmlFor="name-search">Guest name</label><input id="name-search" value={search} onChange={e=>setSearch(e.target.value)} minLength={2} required/><button className="button" disabled={busy}>Find guest</button></form></div>{matches.map(g=><button className="search-match" key={g.id} onClick={()=>void lookup(g.passToken)}><strong>{g.name}</strong><span>{g.status} · {g.checkedIn}/{g.allowedGuests} entered</span></button>)}</main>;
}
